-- MySQL Script generated by MySQL Workbench
-- Sun Jun 11 21:57:10 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MusicPro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MusicPro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MusicPro` DEFAULT CHARACTER SET utf8 ;
USE `MusicPro` ;

-- -----------------------------------------------------
-- Table `MusicPro`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MusicPro`.`Productos` (
  `idProducto` INT NOT NULL,
  `Nombre_pr` VARCHAR(45) NULL,
  `Marca_pr` VARCHAR(45) NULL,
  `Descripcion_pr` VARCHAR(45) NULL,
  `Precio_pr` INT NULL,
  `Sku_pr` VARCHAR(45) NULL,
  `Modelo_pr` VARCHAR(45) NULL,
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MusicPro`.`Categoria_Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MusicPro`.`Categoria_Producto` (
  `idCategoria_Producto` INT NOT NULL,
  `Nombre_capr` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategoria_Producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MusicPro`.`Producto_has_Categoria_Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MusicPro`.`Producto_has_Categoria_Producto` (
  `Producto_idProducto` INT NOT NULL,
  `Categoria_Producto_idCategoria_Producto` INT NOT NULL,
  PRIMARY KEY (`Producto_idProducto`, `Categoria_Producto_idCategoria_Producto`),
  INDEX `fk_Producto_has_Categoria_Producto_Categoria_Producto1_idx` (`Categoria_Producto_idCategoria_Producto` ASC) VISIBLE,
  INDEX `fk_Producto_has_Categoria_Producto_Producto_idx` (`Producto_idProducto` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_has_Categoria_Producto_Producto`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `MusicPro`.`Productos` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_has_Categoria_Producto_Categoria_Producto1`
    FOREIGN KEY (`Categoria_Producto_idCategoria_Producto`)
    REFERENCES `MusicPro`.`Categoria_Producto` (`idCategoria_Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
